server:
  port: 3741

spring:
  ## Configuration Gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://travelease-admin.netlify.app/, http://localhost:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: 'Origin, X-Requested-With, Content-Type, Accept, Z-Key'
            maxAge: 3600

      routes:
        # Hotel - Admin
        - id: Get Detail Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/{hotelId}
            - Method=GET
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        - id: List Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel
            - Method=GET

        - id: Approve Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/approve/{hotelId}
            - Method=POST
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        - id: Reject Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/reject/{hotelId}
            - Method=POST
          filters:
            - AddRequestParameter=hotelId, {hotelId}

  main:
    web-application-type: reactive
