server:
  port: 3741
  ssl:
    key-store: classpath:admin-https.p12
    key-store-password: capstonevlu
    key-store-type: PKCS12
    key-alias: admin-https
    key-password: capstonevlu
    enabled: true

##trust store location
#trust:
#  store: classpath:admin-https.p12
#  password: capstonevlu

spring:
  ## Configuration Gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://travelease-admin.netlify.app/, *"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - POST
              - GET

      routes:
        # Hotel - Admin
        - id: Get Detail Hotel
          uri: http://10.148.0.9:30246
          predicates:
            - Path=/admin/api/approval-hotel/{hotelId}
            - Method=GET
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        - id: List Hotel
          uri: http://10.148.0.9:30246
          predicates:
            - Path=/admin/api/approval-hotels
            - Method=GET

        - id: List Approved Hotel
          uri: http://10.148.0.4:30246
          predicates:
            - Path=/admin/api/approve-hotels
            - Method=GET

        - id: Approve Hotel
          uri: http://10.148.0.9:30246
          predicates:
            - Path=/admin/api/approval-hotel/approve/{hotelId}
            - Method=POST
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        - id: Reject Hotel
          uri: http://10.148.0.9:30246
          predicates:
            - Path=/admin/api/approval-hotel/reject/{hotelId}
            - Method=POST
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        # Facility - Admin
        - id: Get Facilities
          uri: http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facilities
            - Method=GET

        - id: Add Facilities
          uri: http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facility/add
            - Method=POST

        - id: Update Facilities
          uri: http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facility/update/{id}
            - Method=POST
          filters:
            - AddRequestParameter=id, {id}

        - id: Delete Facilities
          uri : http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facility/delete/{id}
            - Method=POST
          filters:
            - AddRequestParameter=id, {id}

        - id: Get Facilities Type
          uri: http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facility-type
            - Method=GET

        - id: Add Facilities Type
          uri: http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facility-type/add
            - Method=POST

        - id: Update Facilities Type
          uri: http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facility-type/update/{id}
            - Method=POST
          filters:
            - AddRequestParameter=id, {id}

        - id: Delete Facilities Type
          uri: http://10.148.0.9:28645
          predicates:
            - Path=/admin/api/facility-type/delete/{id}
            - Method=POST
          filters:
            - AddRequestParameter=id, {id}

        # Login
        - id: Login
          uri: http://10.148.0.9:2910
          predicates:
            - Path=/admin/api/auth/login
            - Method=POST

        # Register
        - id: Sign Up
          uri: http://10.148.0.9:2910
          predicates:
            - Path=/admin/api/auth/sign
            - Method=POST

        # Get Ticket
        - id: Get Ticket
          uri: http://10.148.0.9:16497
          predicates:
            - Path=/admin/api/tickets
            - Method=GET

        # Get Users
        - id: Get Users
          uri: http://10.148.0.9:16497
          predicates:
            - Path=/admin/api/users
            - Method=GET
  main:
    web-application-type: reactive
