server:
  port: 3741
  ssl:
    key-store: classpath:local-https.p12
    key-store-password: capstonevlu
    key-store-type: PKCS12
    key-alias: local-https
    key-password: capstonevlu
    enabled: true

##trust store location
#trust:
#  store: classpath:admin-https.p12
#  password: capstonevlu

spring:
  ## Configuration Gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://travelease-admin.netlify.app/, *"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: 'Origin, X-Requested-With, Content-Type, Accept, Z-Key'
            maxAge: 3600

      routes:
        # Hotel - Admin
        - id: Get Detail Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/{hotelId}
            - Method=GET
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        - id: List Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel
            - Method=GET

        - id: Approve Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/approve/{hotelId}
            - Method=POST
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        - id: Reject Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/reject/{hotelId}
            - Method=POST
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        # Facility - Admin
        - id: Get Facilities
          uri: http://10.148.0.5:28645
          predicates:
            - Path=/admin/api/hotel-facility
            - Method=GET

        - id: Add Facilities
          uri: http://10.148.0.5:28645
          predicates:
            - Path=/admin/api/hotel-facility/add
            - Method=POST

        - id: Update Facilities
          uri: http://10.148.0.5:28645
          predicates:
            - Path=/admin/api/hotel-facility/update/{id}
            - Method=POST
          filters:
            - AddRequestParameter=id, {id}

        - id: Delete Facilities
          uri : http://10.148.0.5:28645
          predicates:
            - Path=/admin/api/hotel-facility/delete/{id}
            - Method=POST
          filters:
            - AddRequestParameter=id, {id}

  main:
    web-application-type: reactive
