server:
  port: 3741

spring:
  ## Configuration Gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://35.198.227.141:3741"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # Hotel - Admin
        - id: Get Detail Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/{hotelId}
            - Method=GET
          filters:
            - AddRequestParameter=hotelId, {hotelId}

        - id: List Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel
            - Method=GET

        - id: Approve Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/approve/{hotelId}
            - Method=PUT
          filters:
            - AddRequestParameter=hotelId, {hotelId}
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - POST
              allowedHeaders: '*'
              maxAge: 30

        - id: Reject Hotel
          uri: http://10.148.0.5:30246
          predicates:
            - Path=/admin/api/approval-hotel/reject/{hotelId}
            - Method=PUT
          filters:
            - AddRequestParameter=hotelId, {hotelId}

  main:
    web-application-type: reactive
